package hrts3;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import com.itextpdf.text.*;



public class Guest extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int bprice = 0;
    int rprice = 0;   
    int overallprice = 0;
    int id;
    String tmp;
    
    public Guest() {
        initComponents();
        con = db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2-getWidth()/2,size.height/2-getHeight()/2);
        btnupdate.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtrequest = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        roomno = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        roomtype = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bed = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        reservetype = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        status = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "GUEST", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(255, 153, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtfirstname.setBackground(new java.awt.Color(255, 255, 255));
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 115, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        txtlastname.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 115, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Request/s:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtrequest.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtrequest);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 313, 160));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Phone no:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtphoneno.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 115, -1));

        lblid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblid.setForeground(new java.awt.Color(0, 0, 0));
        lblid.setText("#");
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("id #:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 107, 420, 340));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "ROOM", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(255, 153, 153))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Room no:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 65, -1, -1));

        roomno.setBackground(new java.awt.Color(255, 255, 255));
        roomno.setForeground(new java.awt.Color(0, 102, 102));
        roomno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        roomno.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                roomnoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoActionPerformed(evt);
            }
        });
        jPanel3.add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 62, 113, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Room type:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 105, -1, -1));

        roomtype.setBackground(new java.awt.Color(255, 255, 255));
        roomtype.setForeground(new java.awt.Color(0, 102, 102));
        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe", "Connecting", "Suite", "" }));
        roomtype.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                roomtypePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel3.add(roomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 102, 113, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Bed:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 145, 36, -1));

        bed.setBackground(new java.awt.Color(255, 255, 255));
        bed.setForeground(new java.awt.Color(0, 102, 102));
        bed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Double-Double", "King", "Queen" }));
        bed.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bedPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel3.add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 142, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Price");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 176, -1, -1));

        Price.setBackground(new java.awt.Color(255, 255, 255));
        Price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Price.setForeground(new java.awt.Color(0, 0, 0));
        Price.setText("--Price--");
        jPanel3.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 176, 113, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Status:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Reservation Type:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 207, -1, -1));

        reservetype.setBackground(new java.awt.Color(255, 255, 255));
        reservetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Immediate", "Reservation" }));
        reservetype.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                reservetypePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        reservetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservetypeActionPerformed(evt);
            }
        });
        jPanel3.add(reservetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 204, 151, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Check in:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 238, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Check out:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 272, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Days:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        day.setBackground(new java.awt.Color(255, 255, 255));
        day.setForeground(new java.awt.Color(0, 102, 102));
        day.setText("1");
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        day.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dayKeyReleased(evt);
            }
        });
        jPanel3.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 29, -1));

        checkin.setDateFormatString("MM/dd/yyyy");
        jPanel3.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 238, 160, -1));

        checkout.setAutoscrolls(true);
        checkout.setDateFormatString("MM/dd/yyyy");
        jPanel3.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 272, 160, -1));

        status.setText("--Status--");
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 107, 470, 340));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setForeground(new java.awt.Color(102, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsearch.setForeground(new java.awt.Color(0, 102, 102));
        txtsearch.setText("Search");
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel4.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 37, 89, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("X");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 37, 33, -1));

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 29, 51, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("GUEST FORM");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 14, 254, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 31, 900, 70));

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, -1, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("PRINT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        btndel.setText("DELETE");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainMenu a = new MainMenu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void reservetypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_reservetypePopupMenuWillBecomeInvisible
      
    }//GEN-LAST:event_reservetypePopupMenuWillBecomeInvisible

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
    
        String sql = "insert into Guest(GuestId,FirstName, LastName, PhoneNo, CheckIn, CheckOut, Request) values (?, ?, ?, ?, ?, ? ,?)";
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        
        try{
        pst = con.prepareStatement(sql);
        pst.setString(1, txtid.getText());
        pst.setString(2, txtfirstname.getText());
        pst.setString(3, txtlastname.getText());
        pst.setString(4, txtphoneno.getText());
        String checkin1 = formatter.format(checkin.getDate());
        String checkin2 = formatter.format(checkout.getDate());
        pst.setString(5, checkin1);
        pst.setString(6, checkin2);
        pst.setString(7, txtrequest.getText());
        pst.execute();
          
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    } finally {
        try{
            pst.close();
            rs.close();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }
    try{
        String sql2 = "select GuestId from Guest where (GuestId = ?)";
        pst = con.prepareStatement(sql2);
        pst.setString(1,txtid.getText());
        rs=pst.executeQuery();
        id = rs.getInt(1);
    }catch(Exception e){
        
    }finally{
        try{
            pst.close();
            rs.close();
        }catch(Exception e){
            
        }
    }
 
    GuestId.guestid = id;
    
    String sql2 = "insert into Room (GuestId, RoomNo, RoomType, Bed, Days, ReservationType, Status, Payment) values (?,?,?,?,?,?,?,?)";
    try{
        pst = con.prepareStatement(sql2);
        pst.setInt(1, GuestId.guestid);
        pst.setString(2, (String)roomno.getSelectedItem());
        pst.setString(3, (String)roomtype.getSelectedItem());
        pst.setString(4, (String)bed.getSelectedItem());
        pst.setInt(5,Integer.parseInt(day.getText()));
        pst.setString(6, (String)reservetype.getSelectedItem());
        pst.setString(7, "Occupied");
        pst.setInt(8,Integer.parseInt(Price.getText()));
        pst.execute();
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    finally{
        try{
            pst.close();
        }catch(Exception e){
            
        }
    
    }
    
    
    try{
        String roomnum = (String)roomno.getSelectedItem();
        String avail = "Occupied";
        
        String sql3 = "update RoomAvailability set RoomNumber = '"+roomnum+"',Status='"+avail+"' where RoomNumber = '"+roomnum+"'";
        pst = con.prepareStatement(sql3);
        pst.execute();
        JOptionPane.showMessageDialog(null,"Data saved.");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    finally{
        try{
            pst.close();
        }catch(Exception e){
            
        }
    }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
      txtsearch.setText("");       
    }//GEN-LAST:event_txtsearchMouseClicked

    private void roomnoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_roomnoPopupMenuWillBecomeInvisible
        String tmp = (String)roomno.getSelectedItem();
        String sql = "select * from RoomAvailability where RoomNumber = ?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1,tmp);
            rs = pst.executeQuery();
            if(rs.next()){
                String roomnumber= rs.getString("Status");
                status.setText(roomnumber);
                if(status.getText().equals("Occupied")){
                    status.setForeground(Color.red);
                    btnsave.setEnabled(false);
                }else if(status.getText().equals("Available")){
                  status.setForeground(Color.green);
                  btnsave.setEnabled(true);
                }
            }
        }catch(Exception e){
            
        }finally{
            try{
                pst.close();
                rs.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_roomnoPopupMenuWillBecomeInvisible

    private void bedPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bedPopupMenuWillBecomeInvisible
        String tmp = (String)roomno.getSelectedItem();
        String sql = "select * from Bedprice where Bed = ?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1,tmp);
            rs= pst.executeQuery();
            if(rs.next()){
                String bedprice = rs.getString("BedPrice");
                bprice = Integer.parseInt(bedprice);
                overallprice = bprice + rprice;
                Price.setText(String.valueOf(overallprice));               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } finally{
            try{
                pst.close();
                rs.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_bedPopupMenuWillBecomeInvisible

    private void roomtypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_roomtypePopupMenuWillBecomeInvisible
        String tmp = (String)roomtype.getSelectedItem();
        String sql = "select * from Roomprice where Room = ?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1,tmp);
            rs= pst.executeQuery();
            if(rs.next()){
                String roomprice = rs.getString("Price");
                rprice = Integer.parseInt(roomprice);
                overallprice = bprice + rprice;
                Price.setText(String.valueOf(overallprice));
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } finally{
            try{
                pst.close();
                rs.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_roomtypePopupMenuWillBecomeInvisible

    private void reservetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservetypeActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void dayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dayKeyReleased
        int days = Integer.parseInt(day.getText());
        overallprice = bprice + rprice * days;
        Price.setText(String.valueOf(overallprice));
    }//GEN-LAST:event_dayKeyReleased

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update", JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
                String id = txtid.getText();
                String fname = txtfirstname.getText();
                String lname = txtlastname.getText();
                String phone = txtphoneno.getText();
                String req = txtrequest.getText();
                DateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
                String chi = String.valueOf(sdf.format(checkin.getDate()));
                String cho = String.valueOf(sdf.format(checkout.getDate()));
                
                String sql1 = "update Guest set GuestId = '"+id+"',FirstName='"+fname+"',LastName='"+lname+"',Phoneno='"+phone+"',Request='"+req+"',CheckIn='"+chi+"',CheckOut='"+cho+"' where GuestId ='"+id+"'";
                pst = con.prepareStatement(sql1);
                pst.execute();
            }catch(Exception e){
                
            }finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            
            try{
                String id = txtid.getText();
                String roomnum = (String)roomno.getSelectedItem();
                String roomtyp = (String)roomtype.getSelectedItem();
                String bedd = (String)bed.getSelectedItem();
                String reservetyp = (String)reservetype.getSelectedItem();
                String pricee = Price.getText();
                String stats = "Occupied";
                String days = day.getText();
                
                String sql2 = "update Room set GuestId = '"+id+"',RoomNo='"+roomnum+"',RoomType='"+roomtyp+"',Bed='"+bedd+"',ReservationType='"+reservetyp+"',Payment='"+pricee+"',Status='"+stats+"',Days='"+days+"' where GuestId = '"+id+"'";
                pst = con.prepareStatement(sql2);
                pst.execute();
            }catch(Exception e){
                
            }
            finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            
            try{
                String roomnum = (String)roomno.getSelectedItem();
                String avail = "Occupied";
                
                String sql3 = "update RoomAvailability set RoomNumber = '"+roomnum+"',Status='"+avail+"' where RoomNumber = '"+roomnum+"'";
                pst = con.prepareStatement(sql3);
                pst.execute();
            }catch(Exception e){
                
            }finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            
            try{
                String roomnum = tmp;
                String avail = "Available";
                System.out.println(tmp);
                String sql3 = "update RoomAvailability set RoomNumber = '"+roomnum+"',Status='"+avail+"' where RoomNumber = '"+roomnum+"'";
                pst = con.prepareStatement(sql3);
                pst.execute();
                btnupdate.setEnabled(false);
                clearText();
               JOptionPane.showMessageDialog(null, "Record Updated");
            }catch(Exception e){
                
            }finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            
            
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        
        String sql = "select * from Guest where GuestId = ?";
        
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, txtsearch.getText());
            rs = pst.executeQuery();
            
            int id = rs.getInt("GuestId");
            txtid.setText(String.valueOf(id));
            lblid.setText(String.valueOf(id));
            String fname = rs.getString("FirstName");
            txtfirstname.setText(fname);
            String lname = rs.getString("LastName");
            txtlastname.setText(lname);
            int phone = rs.getInt("PhoneNo");
            txtphoneno.setText(String.valueOf(phone));
            String req = rs.getString("Request");
            txtrequest.setText(req);
            String check1 = rs.getString("CheckIn");
            java.util.Date d1 =  new SimpleDateFormat("MM/dd/yyyy").parse((String)check1);
            checkin.setDate(d1);
            String check2 = rs.getString("CheckOut");
            java.util.Date d2 =  new SimpleDateFormat("MM/dd/yyyy").parse((String)check2);
            checkout.setDate(d2);
            btnsave.setEnabled(false);
        }catch(Exception e){
            btnupdate.setEnabled(false);
            lblid.setText("#");
            clearText();
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        
        String sql2 = "select * from Room where GuestId = ?";
        
        try{
            pst = con.prepareStatement(sql2);
            pst.setString(1, txtsearch.getText());
            rs = pst.executeQuery();
            
            String roomnum = rs.getString("RoomNo");
            String roomtyp = rs.getString("RoomType");
            String bedd = rs.getString("Bed");
            int dayy = rs.getInt("Days");
            String reservetyp = rs.getString("ReservationType");
            String stats = rs.getString("Status");
            int paym = rs.getInt("Payment");
            
            roomno.setSelectedItem(roomnum);
            tmp = (String)roomno.getSelectedItem();
            roomtype.setSelectedItem(roomtyp);
            bed.setSelectedItem(bedd);
            day.setText(String.valueOf(dayy));
            reservetype.setSelectedItem(reservetyp);
            status.setText(stats);
            Price.setText(String.valueOf(paym));
            if(status.getText().equals("Occupied")){
                status.setForeground(Color.red);
            }else{
                status.setForeground(Color.green);
            }
        }catch(Exception e){
            btnupdate.setEnabled(false);
            lblid.setText("#");
            clearText();
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        
        
        
        if(lblid.getText().equals("#")){
            btnupdate.setEnabled(false);
            btnsave.setEnabled(true);
        }else{
            btnupdate.setEnabled(true);
            btnsave.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clearText();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this record?","Delete",JOptionPane.YES_NO_OPTION);
        if(a == 0){
            try{
                String sql = "delete from Guest where GuestId = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1,txtid.getText());
                pst.execute();
            }catch(Exception e){
                
            }finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            try{
                String sql = "delete from Room where GuestId = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1,txtid.getText());
                pst.execute();
            }catch(Exception e){
                
            }finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            
            try{
                String sql = "update RoomAvailability set RoomNumber ='"+(String)roomno.getSelectedItem()+"',Status='Available' where RoomNumber='"+(String)roomno.getSelectedItem()+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                clearText();
                JOptionPane.showMessageDialog(null, "Record deleted.");
            }catch(Exception e){
                
            }finally{
                try{
                    pst.close();
                }catch(Exception e){
                    
                }
            }
            
            
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest().setVisible(true);
            }
        });
    }
    
    public void clearText(){
        txtid.setText("");
        txtfirstname.setText("");
        txtlastname.setText("");
        txtphoneno.setText("");
        txtrequest.setText("");
        lblid.setText("#");
        roomno.setSelectedIndex(0);
        roomtype.setSelectedIndex(0);
        bed.setSelectedIndex(0);
        reservetype.setSelectedIndex(0);
        day.setText("");
        status.setText("");
        Price.setText("");
        checkin.setDate(null);
        checkout.setDate(null);
        txtsearch.setText("");
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price;
    private javax.swing.JComboBox<String> bed;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JTextField day;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JComboBox<String> reservetype;
    private javax.swing.JComboBox<String> roomno;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JLabel status;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextPane txtrequest;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
